### ISSUE TITLE
[BUG] I can't limit the clock frequency of my ryzen 5 3500u cpu

### ISSUE THREAD

**Issue by dotienanhvietnam** [JamesCJ60/Universal-x86-Tuning-Utility#102]
my ryzen 5 3500u has a base clock frequency of 2.1ghz and when boost is 3.7ghz i want to limit it to 2.1ghz or 2.6 or a number lower than 3.7ghz so that my laptop generates less heat and igpu works more powerful but in settings of universal x86 tuning Utility there is an option to limit cpu clock speed but it must be a cpu that is not working I get the cpu boost feature, but every time I want to turn it on and off, I have to turn off the computer and use the usb to enter the bios, which is quite inconvenient.
Thank you for making this great app hope you will improve it in the future ❤
![image](https://github.com/JamesCJ60/Universal-x86-Tuning-Utility/assets/132206353/a42344ff-b5ee-4496-9d44-0da421f6077e)

**Comment by sjekk** [comment]
Just set the temperature limit at 65 and it will max out at 2.6 ghz
