### ISSUE TITLE
Latest release has a virus

### ISSUE THREAD

**Issue by arrowJW** [JamesCJ60/Universal-x86-Tuning-Utility#105]
After I downloaded the latest release (Universal.x86.Tuning.Utility.V2.msi)
I ran it through Virustotal.com and here's the result I got.
[https://www.virustotal.com/gui/file/417be77a03a6e1ae98be360de4616262f5f87da174fb485daad6f952914bf404](url)

Out of the 57 security vendors, Rising detected this signature.
**HackTool.VulnDriver/x64!1.D7DB (CLASSIC)**

**Comment by JamesCJ60** [comment]
It is just a false positive. You can happily look through the source code if you are sceptical.
