### ISSUE TITLE
[FEATURE REQUEST]  Support for 7045HX Dragon Range CPUs in V2.0

### ISSUE THREAD

**Issue by haseeeib** [JamesCJ60/Universal-x86-Tuning-Utility#106]
Please add support for 7045HX series laptop CPUs in version 2.0 of UXTU.  I'd be happy to beta test as well (7945HX).
(Thanks for the great work!)

**Comment by TeslaWiki** [comment]
could you add support for 7945HX DR5 RAM overclocking ?

**Comment by dream2333** [comment]
same demand
my cpu model is 7840hs,  I'd be glad to provide support

**Comment by JamesCJ60** [comment]
This specific issue is being closed because it is a duplicate of an existing issue someone else has reported.
