### ISSUE TITLE
[BUG] No Profiles generate or create custom ones 

### ISSUE THREAD

**Issue by pcwizard7** [JamesCJ60/Universal-x86-Tuning-Utility#111]
I have an ASUS Strix  17 2022 Model which has an i9 12900H and the only things I can set are the TDP of the CPU and temperature limit then once I try to save a profile it said it's been saved but it hasn't and there are no presets generated or custom profiles i ve tried to saved 

So it can't save profiles at all on my Laptop but it does apply the setting

**Comment by Edelf** [comment]
Same is happening here.
My model https://www.msi.com/Laptop/GS63VR-7RG-Stealth-Pro/

**Comment by JamesCJ60** [comment]
Hi, when I get some free time I’ll take a look at this for you.

**Comment by JamesCJ60** [comment]
Hi, this should now be fixed with the last couple of updates.
