### ISSUE TITLE
[BUG] The custom settings of the program are unstable or have no effect: Losing effect within one minute or less

### ISSUE THREAD

**Issue by Arc-2023** [JamesCJ60/Universal-x86-Tuning-Utility#112]
**Describe the bug**
The custom preset and adaptive mode settings only take effect for a short period of time, about 1 minute, then they stop working.

**To Reproduce**
Steps to reproduce the behaviour:
Set custom preset or adaptive mode
Wait for about 1 minute
The settings stop working

**Expected behaviour**
The custom preset and adaptive mode settings are expected to keep working continuously, instead of stop working after 1 minute.

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version:  Windows 11 Ryzen 5600H Lenovo LEGION

**Additional context**
The Image Scaling effects seem to randomly stop applying. This does not happen with other settings. Restarting the program is the only way to re-enable adaptive mode once it stops working.

**Comment by Arc-2023** [comment]
> i guess the Legion Zone have conflicts with this app.

I didn't even install this

**Comment by JamesCJ60** [comment]
Hi, for those case you will need to enable auto-reapply in the settings menu.
