### ISSUE TITLE
[BUG] text inputs near all tuning sliders are corrected immediately

### ISSUE THREAD

**Issue by grantfanian** [JamesCJ60/Universal-x86-Tuning-Utility#113]
**Describe the bug**
The APU Power Tuning power limit values cannot be set reliably through typing the numbers in, because they round up as you type.

**To Reproduce**
Try to type in the number "31" into the STAPM Power Limit textbox
1. try to delete everything (just backspace)
2. input goes to "5" as it's the minimum value
- try to input 3 after the 5 (so the value is "53") and remove the leading 5? no, it corrects it to 5 anyways
- try to type "31" in so the value is "531" and then delete the leading "5"? no, the limit is 300, it corrects the value to that immediately
(any other combinations logically won't work well as well)

The only remaining option in this case is to set the value with the slider, which is awkward and makes the text box (almost) useless

**Expected behavior**
The correction should be performed only when the input is being confirmed, e.g. when the textbox loses focus or when user presses the Enter key

**Desktop (please complete the following information):**
 - OS Version: Windows 11 22H2 (22621.1992)
 - APU: 6600HS (Lenovo IdeaPad 5 14ARH7 / 82SJ)
 - UXTU version: 2.0.0.22 (latest release)

**Additional context**
I think just fixing this can improve UX a lot.

**Comment by JamesCJ60** [comment]
I have no control over this as it is managed by the WPF UI package used for the GUI design.
