### ISSUE TITLE
[FEATURE REQUEST] Add to adaptive mode the ability to autorun at program startup

### ISSUE THREAD

**Issue by githihfuhg** [JamesCJ60/Universal-x86-Tuning-Utility#115]
**Is your feature request related to a problem? Please describe.**
When starting the program, it is always necessary to start "adapive mode" manually.

**Describe the solution you'd like**
It would be nice to add a check box that would allow you to configure the "adapive mode" behavior when launching the program.

**Comment by JamesCJ60** [comment]
This has been added as of the latest build.
