### ISSUE TITLE
[FEATURE REQUEST] Add controller operated bindings

### ISSUE THREAD

**Issue by AHandheldFan** [JamesCJ60/Universal-x86-Tuning-Utility#117]
I'd like for you to add the ability to use the panel with just a controller, especially to toggle Magpie FSR on and off and other display settings/functions.
Currently I don't see any option for that. Bring it more inline with handheld control panel in that regard.

**Comment by JamesCJ60** [comment]
Hi, this version will not be optimised for handhelds. Please use UXTU Handheld instead.

**Comment by AHandheldFan** [comment]
Wtf doss this have to do with handhelds?
Never once did I mention I was using a handheld PC
