### ISSUE TITLE
[BUG] 2.0.1 update loop

### ISSUE THREAD

**Issue by kilrah** [JamesCJ60/Universal-x86-Tuning-Utility#119]
Installed from 2.0.1 releases

Home page shows 2.0.1

![image](https://github.com/JamesCJ60/Universal-x86-Tuning-Utility/assets/6065069/1a004748-b49a-400e-b891-6c783881e53a)

Settings however shows 2.0.0.24 and says an update is available

![image](https://github.com/JamesCJ60/Universal-x86-Tuning-Utility/assets/6065069/e60633e5-5fe9-4754-affa-eddc8c5effc0)

Download update reinstalls the same thing (actually only get options to Repair or Remove from the installer)

**Comment by ensarisik** [comment]
An an other bug is this notification

![explorer_KXi21Z8C69](https://github.com/JamesCJ60/Universal-x86-Tuning-Utility/assets/141909414/ea3d5425-95d7-4ebc-92a2-8d007489801a)

**Comment by kilrah** [comment]
Fixed in https://github.com/JamesCJ60/Universal-x86-Tuning-Utility/commit/1764b2268008d4ae796d2f9fac57919a9767a4e1
