### ISSUE TITLE
CPU is working 1.5x slower even after reinstall

### ISSUE THREAD

**Issue by carlo323** [JamesCJ60/Universal-x86-Tuning-Utility#120]
I tried extreme presets and after that my CPU (Ryzen 9 7950X) is working 1.5 times slower even after uninstalling your solfware.

**Comment by Lahm919** [comment]
I think the motherboard's official software is OK.
BTW, I installed once, the computer crashed, bios crashed. 
I guess the msi center and its RM sdk conflicts with UXTU.
