### ISSUE TITLE
[FEATURE REQUEST] Adaptive Mode

### ISSUE THREAD

**Issue by sjekk** [JamesCJ60/Universal-x86-Tuning-Utility#122]
**Is your feature request related to a problem? Please describe.**
I really like the new adaptive mode you guys implemented. However I have to manually start adaptive mode every time the PC is started up.

**Describe the solution you'd like**
Could you make a function that automatically start the adaptive profile on (windows) startup?

**Describe alternatives you've considered**
Implement the features of adaptive mode in the custom settings and implement them in a profile.

**Comment by JamesCJ60** [comment]
This has been added as of the latest build.
