### ISSUE TITLE
[FEATURE REQUEST] Dragon Range

### ISSUE THREAD

**Issue by SoonpilHOng** [JamesCJ60/Universal-x86-Tuning-Utility#131]
Is there no possibility of supporting for the Dragon Range CPUs at all?

**Comment by cidiousx** [comment]
It's the AMD CPU that needs this tool the most. But the dev doesn't seem to be interested at all to add it. Keeps saying due to back-end rewrite for months now. I have given up hope. It is what it is.

**Comment by ASURA715** [comment]
It's the AMD CPU that needs this tool the most

**Comment by JamesCJ60** [comment]
At this current time, no one is aware of the addresses needed to communicate with Dragon Range’s SMU.

**Comment by fscottcopeland** [comment]
@JamesCJ60 see https://github.com/irusanov/SMUDebugTool - I've got per core CO working on my 7945HX using this tool.

**Comment by fscottcopeland** [comment]
> @JamesCJ60 see https://github.com/irusanov/SMUDebugTool - I've got per core CO working on my 7945HX using this tool.

Reminder @JamesCJ60
