### ISSUE TITLE
[BUG] Updating creates new shortcut even if it already exists

### ISSUE THREAD

**Issue by knasiotis** [JamesCJ60/Universal-x86-Tuning-Utility#136]
I do not know if this has been fixed, however I just updated to version 2.1.0.0 and it created a second identical shortcut. I believe this is probably trivial to fix, just a small qol change to avoid removing the redundant shortcut manually.
Thanks in advance!

**Comment by LiberteCzech** [comment]
I upgrade from 2.1.0 to 2.1.1 and no extra shortcut, so it is propably working.

**Comment by knasiotis** [comment]
are you using windows 11?

**Comment by LiberteCzech** [comment]
Yes I use the latest 11 stable.
![image](https://github.com/JamesCJ60/Universal-x86-Tuning-Utility/assets/13797292/124a5243-1151-4bd5-b27f-71a96014598d)

**Comment by knasiotis** [comment]
same here, weird, i've been having the same issue on multiple versions not only 2.1.1

**Comment by JamesCJ60** [comment]
Hi, the installer package is maintained by Microsoft and any bugs have to be addressed by them.
