### ISSUE TITLE
[BUG] Installer Open and then Closes

### ISSUE THREAD

**Issue by popepenguin** [JamesCJ60/Universal-x86-Tuning-Utility#137]
**Describe the bug**
Trying to run the installer just causes the installer to open and then immediately close. Nothing happens, it's not in the taskbar or in the background. 

**To Reproduce**
Double click installer 

**Expected behaviour**
I expected a menu or the installer to open up, but it just open and then closes. 

**Desktop (please complete the following information):**
Windows 11 22H2

**Comment by LiberteCzech** [comment]
If you think 2.1.1 update, Update work for me.

**Comment by JamesCJ60** [comment]
Hi, the installer package is maintained by Microsoft and any bugs have to be addressed by them.
