### ISSUE TITLE
[BUG] Calling 

### ISSUE THREAD

**Issue by HackifyPhython** [JamesCJ60/Universal-x86-Tuning-Utility#138]
**Describe the bug**
when i start adaptive mode this happens

![image](https://github.com/JamesCJ60/Universal-x86-Tuning-Utility/assets/105222565/1fd96d61-8ff5-47e4-88d7-b492174da2b1)

**Comment by NekoAlosama** [comment]
I have the same issue. I'm not sure whether the commit from 7 hours ago is a fix to it, but I'll just be using v2.1.0 until v2.1.2 comes out.

**Comment by JamesCJ60** [comment]
Hi, that has been fixed as of v2.1.2.
