### ISSUE TITLE
App crashing frequently[BUG]

### ISSUE THREAD

**Issue by SWi7CHbladE** [JamesCJ60/Universal-x86-Tuning-Utility#140]
**Describe the bug**
The app seems to crash on my dell 7577, with i7 7700hq and gtx1060 while some game crashes, eg: Race Driver Grid

**Comment by BenedictHW** [comment]
I have the same problem with the latest version 2.1.3. Rather it crashes on start up. I see the system tray icon for a split second before the application crashes. The most recent version that works is version 2.0 .4. I'm not too sure how to locate the log files but if you can plug me in the right direction i'd be happy to help debug why this is.

**Comment by aniketgpt** [comment]
I also have the same issue using the utility on Ryzen 7 7745HX, it keeps crashing as soon as opening the application .
