### ISSUE TITLE
[BUG] Cannot Join Discord Server

### ISSUE THREAD

**Issue by SiddharthManthan** [JamesCJ60/Universal-x86-Tuning-Utility#141]
**Describe the bug**
Cannot Join Discord Server

**To Reproduce**
Try to join the discord server using the invite link in the Readme

**Expected behaviour**
Can join the server

**Screenshots**
![image](https://github.com/JamesCJ60/Universal-x86-Tuning-Utility/assets/91691810/e758af0a-a4a0-410a-998e-1178a4a0be0b)

**Comment by NekoAlosama** [comment]
There are two Discord links in the README. The first one seems to be correct, the second one is invalid.

**Comment by JamesCJ60** [comment]
This should now be fixed. Thank you for bring it to my attention!
