### ISSUE TITLE
[BUG] Asus g14 ga401qm dedicated graphics

### ISSUE THREAD

**Issue by MrHumanRebel** [JamesCJ60/Universal-x86-Tuning-Utility#142]
As soon as I launch the utility, from eco mode it turns back on the dedicated GPU. While on battery it is very bad. After changing back to eco mode in armoury crate, after a few minutes it changes back again to the dedicated GPU by itself.

**Comment by JamesCJ60** [comment]
UXTU has the ability to override and even replace Armoury Crate. Please make sure you match UXTU with your Armoury Crate settings if you are using auto reapply.
