### ISSUE TITLE
[FEATURE REQUEST] RAM overclock

### ISSUE THREAD

**Issue by FNsi** [JamesCJ60/Universal-x86-Tuning-Utility#145]
**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

DDR overclocking

**Describe alternatives you've considered**

 SPD backup, edit and flash...
 Or XMP support?

**Additional context**

I think... it's hard but really useful in any case...

**Comment by squee666** [comment]
wouldnt be feasible its hard defined by bios
if you need to do that closest you can do is use smokeless UMAF and do it yourself https://github.com/DavidS95/Smokeless_UMAF

**Comment by FNsi** [comment]
> wouldnt be feasible its hard defined by bios/uefi
> 
> if you need to do that closest you can do is use smokeless UMAF and do it yourself https://github.com/DavidS95/Smokeless_UMAF

Nah, I don't think that works universally. 

Meanwhile I can do it by setup_var manually, but that's complicated to use.
