### ISSUE TITLE
[BUG] The app wont even run anymore after updating it.

### ISSUE THREAD

**Issue by eMerchant717** [JamesCJ60/Universal-x86-Tuning-Utility#148]
After udpdating the app from the software, the installer download the latest ver, and then install it. But the UXTU not running anymore. So, I restart the laptop, try to run the UXTU, but nothing happen. The mouse cursor only only react by showing loading circle. That is. The app not run, I checked on taskbar, nothing.

My specs:
ASUS X505Z (laptop)
Ryzen 3 2200U
Windows 10 20h2

**Comment by KovacevicAleksa** [comment]
Same
Win 11
Ryzen 7 3700u

**Comment by JamesCJ60** [comment]
This should now be fixed as of version 2.2.1.
