### ISSUE TITLE
[BUG] Can't close RTSS on V2.2.0

### ISSUE THREAD

**Issue by fredinj** [JamesCJ60/Universal-x86-Tuning-Utility#149]
**Describe the bug**
RTSS keeps getting relaunched after updating to V2.2.0 even though track games is turned off in settings.

**Expected behaviour**
RTSS shouldn't be launched if game tracking is off.

**Desktop (please complete the following information):**
 - OS Version: Windows 11 22H2

**Comment by JamesCJ60** [comment]
This should now be fixed as of version 2.2.1.
