### ISSUE TITLE
Please give me a link to the NET framework I need.

### ISSUE THREAD

**Issue by Wozza2014** [JamesCJ60/Universal-x86-Tuning-Utility#151]
Hi.

The Universal-x86-Tuning-Utility installer opens a page with many different NET installers.  There is SDK, ASP.NET Core Runtime 8.0.0, .NET Desktop Runtime 8.0.0, .NET Runtime 8.0.0.  

Which one do I need to download??

I've installed ASP.NET Core Runtime 8.0.0 and also tried .NET Runtime 8.0.0 and its still asking for NET framework when I try to install Universal-x86-Tuning-Utility.

Please can you give me a link to the exact one.

Thanks.

**Comment by Wozza2014** [comment]
Hi.

Thanks for that.  One more thing.  Does the runtime need to be the x86 version?  I take it the apu tuning app is 32-bit due to the x86 being in the name?

**Comment by JamesCJ60** [comment]
You need the 64bit version.
