### ISSUE TITLE
[FEATURE REQUEST] Undervolt 6xxx gen apu's

### ISSUE THREAD

**Issue by SausageKiller218** [JamesCJ60/Universal-x86-Tuning-Utility#159]
i'd like to undervolt (curve adjustment will be fine) my 6800H, or gpu in it.
per-core curve optimiser in uxtu is not working for me.

**Comment by JamesCJ60** [comment]
AMD only allows Ryzen 9 mobile APUs from the 5000 series onwards to be undervolted.

**Comment by SausageKiller218** [comment]
> AMD only allows Ryzen 9 mobile APUs from the 5000 series onwards to be undervolted.

so only a Ryzen 9 5xxx and onwards?
sad
