### ISSUE TITLE
HP 255 G8 Laptop: Inconsistent TDP Performance on Windows 11

### ISSUE THREAD

**Issue by HamzaYslmn** [JamesCJ60/Universal-x86-Tuning-Utility#163]
**Describe the bug**
It's not exactly a bug.
I have an HP 255 G8 laptop. But ReApply is not working properly on this laptop.
The device is normally 15W, I downloaded the app to use 25W. 
Eco mode works very well and locks it around 5-6W. 
But... In Balanced mode, it is 25W for a while. I get a constant 23W and above, but after 30 seconds the device drops back to 15W. 
As the wattage drops, if I take it to eco and balanced again, it goes up to 23W again. 

**To Reproduce**
Open the app
choose balanced
Play with 25W for up to 30 seconds
then it drops back down to 15W.
Then back to eco and then balanced.
Play with 25W for 30 seconds.
And so on...

**Expected behaviour**
When my device is running at 25W, the temperature does not exceed 68 degrees. I monitor the temperatures with Hw info. Every temperature is in the safe, even cold range. So I want to increase TDP. 

**Screenshots**
no need to

**Desktop (please complete the following information):**
 - OS Version: Windows 11 22H2

**Additional context**
if I make the fast and slow boost time 1024 I get a boost time over 30 seconds. but after a while it drops to 15W again.

**Comment by JamesCJ60** [comment]
HP sets hard maximum limits for the PL0, PL1, and PL2 on their laptops that cannot be overridden with higher values.
