### ISSUE TITLE
R5 3450U @ 65W @ 99-100C Max Load - Willing to test extremes, for science. Devs!

### ISSUE THREAD

**Issue by VaxYourDamnKids** [JamesCJ60/Universal-x86-Tuning-Utility#17]

**Comment by VaxYourDamnKids** [comment]
Put liquid metal on it, btw & runs @ 3.5GHz 4/8c + 1200Mhz iGPU under 100% usage, steady and no drops ~99-100C. No shutting down or anything.

_I mine with that mofo just for the hell of it._ 

 **DEVS, let's OC/UV this SOB!**

![Screenshot_20221111_080231](https://user-images.githubusercontent.com/94568509/201451471-84514dea-a1a6-481c-8a1c-85e633ab15fb.png)

**Comment by JamesCJ60** [comment]
3450U is a locked APU so cannot be overclocked

**Comment by VaxYourDamnKids** [comment]
> 3450U is a locked APU so cannot be overclocked

Ah, ok. Thanks for the answer, ese
