### ISSUE TITLE
'Battery saver' preset uses more energy than vanilla setting

### ISSUE THREAD

**Issue by seawee1** [JamesCJ60/Universal-x86-Tuning-Utility#18]
As the title says. I have a Legion 7 with Ryzen 9 5900HX. Using your UXTU tool, I thought I might be able to save energy when on battery mode (through using the `Battery saver` preset), but energy consumption rises from ~18W to ~23-25W once activating the UXTU tool. Is this to be expected?

**Comment by JamesCJ60** [comment]
This should no longer be an issue
