### ISSUE TITLE
Aesthetic Suggestion

### ISSUE THREAD

**Issue by dev-bd** [JamesCJ60/Universal-x86-Tuning-Utility#181]
This isn't really related to a "feature", but bear with me.

I love your application and appreciate all you do; I use it almost daily. However, I noticed that the latest update changed the "premade presets" tab, replacing the picture of an AMD chip with a generic image of a laptop.

I will use the application regardless, but I genuinely think this looks much tackier and believe the old AMD icon was significantly more professional looking and aesthetically pleasing. I also asked two friends about this (not people pleaser types) and they agreed.

At the end of the day it's your project and you can do as you wish, but I feel like most people would prefer the previous icon. Just something to consider for the next update / prerelease if it's not a huge hassle. Once again, thanks for the software and I appreciate your consideration.

**Comment by JamesCJ60** [comment]
Thanks for reporting this as it was a bug. That image should have only been visible if a Framework 16 was detected. The latest beta fixes this issue.
