### ISSUE TITLE
How to remove all applied configuration

### ISSUE THREAD

**Issue by diotriandika** [JamesCJ60/Universal-x86-Tuning-Utility#189]
I've uninstalled UXTU from my device, but idk how to completely remove applied preset after uninstalling it. The major problem i have were at GPU TDP, im using ghelper and usually it runs at 80w at balance mode. But now it start kicking to 100w even 120w. I've tried to restart my computer but still not working.
![image](https://github.com/JamesCJ60/Universal-x86-Tuning-Utility/assets/109568349/0e71018f-3cbf-4227-9a49-d4a36c11cbb4)
![image](https://github.com/JamesCJ60/Universal-x86-Tuning-Utility/assets/109568349/3803da70-4391-4875-b9b6-1425794ce7fe)

**Comment by JamesCJ60** [comment]
Hi, UXTU will not and cannot keep presets applied across system boots nor control GPU power limits.

**Comment by diotriandika** [comment]
Im sorry, but it does 
I have accidentally configured in the Nvidia section on the newest UXTU. After that my gpu TDP Uncapped even in balance mode. In normal situations it should be limited on 80watt, then i reset my laptop and the gpu still uncapped
Please help me, it makes my computer runs hotter rn

**Comment by JamesCJ60** [comment]
Again, there is zero code within UXTU to control the TDP of NVIDIA GPUs.
