### ISSUE TITLE
Clarification about functionality

### ISSUE THREAD

**Issue by philipjan** [JamesCJ60/Universal-x86-Tuning-Utility#2]
Since i keep enabling **Performance Mode** and **undervolt**. Just want to clarify, do I need to **select/click** them everytime the app starts?

![image](https://user-images.githubusercontent.com/8721208/183128022-622f9287-c5b7-444a-adac-8de5c441f5ee.png)

![image](https://user-images.githubusercontent.com/8721208/183128088-cfc27dec-d38f-440a-85b3-25ed3a61fd04.png)

**Comment by philipjan** [comment]
Because as i check on the preset txt file, there's no persisted value for them.

**Comment by philipjan** [comment]
@JamesCJ60

**Comment by JamesCJ60** [comment]
From memory, the power profiles wouldn't need reapplying on boot if your using auto reapply. Curve optimiser needs to be reapplied every boot as a safety measure.

**Comment by philipjan** [comment]
Thank you so much for the response. Appreciated. @JamesCJ60
