### ISSUE TITLE
Application menu starts under the taskbar when it is on the left.

### ISSUE THREAD

**Issue by ae-bogdan** [JamesCJ60/Universal-x86-Tuning-Utility#20]
![image](https://user-images.githubusercontent.com/17846988/205733767-8d9ce7a0-c4f4-4a56-8509-33b6dcfd8492.png)

No way to resize, move... Luckily I have two displays and when I alternate them it somehow magically centers itself.

**Comment by JamesCJ60** [comment]
I’m currently clearing all UXTU V1.0.0 issues now that UXTU V2.0.0 is in beta testing. If the issue still persists in UXTU V2.0.0 feel free to reopen the issue.
