### ISSUE TITLE
[BUG] Crash when opening Custom tab

### ISSUE THREAD

**Issue by berkkrkc09** [JamesCJ60/Universal-x86-Tuning-Utility#203]
**Describe the bug**
I click the Custom tab on the left or on the home page. After clicking it gets stuck here for a few seconds then close/crash.

**To Reproduce**
Steps to reproduce the behaviour:
1. Run the program.
2. Click on 'Custom' button on the left or in the home page.
3. Brace yourself for the crash

**Expected behaviour**
Custom tab should open and show my custom presets.

**Screenshots**
[Screenshot](https://imgur.com/a/NSssmYG)

**Desktop (please complete the following information):**
 - OS Version: Windows 11 Pro 23H2 22631.3593

**Additional context**
Before this started happening I was messing with the curve optimizer in custom presets and BSOD my PC a few times. After a BSOD it started to behave like this. I use [UXTU v2.2.10.0](https://github.com/JamesCJ60/Universal-x86-Tuning-Utility/releases/tag/2.2.10).

**Comment by berkkrkc09** [comment]
Just to inform, The situation is the same after the 2.2.11 update.

**Comment by berkkrkc09** [comment]
I found where logs were saved and wanted to add them to help:
[uxtu_log20240527.txt](https://gist.github.com/berkkrkc09/92e3d3831c105d9205b28743aaf11bc5)
[Runtime.log](https://gist.github.com/berkkrkc09/a08a56338114cf716062b1caa68bedc5)

**Comment by JamesCJ60** [comment]
Hi, your custom preset JSON file has become corrupted, so I would suggest that you delete any preset JSON file found within the installation location to fix this issue.

**Comment by berkkrkc09** [comment]
Thank you so much. This fixed the issue. I was wondering why it seemed empty while looking for an easy fix myself.
