### ISSUE TITLE
[FEATURE REQUEST] Undervolt missing in some CPUs despite enabled support

### ISSUE THREAD

**Issue by ShyVortex** [JamesCJ60/Universal-x86-Tuning-Utility#223]
Hi everyone, I currently own the HP Pavilion Gaming 16 a-0046nl laptop, and as some of you may know, by default it is fully locked, meaning you cannot access any CPU tweaks or customize any power-related options.
That's why I followed [this guide](https://www.reddit.com/r/Hewlett_Packard/comments/o1zxuv/howto_unlock_undervolting_change_timings_on_hp/) when I got the laptop to unlock undervolting etc. on my CPU, which is the Intel Core i7-10750H.
Before trying out UXTU for a few weeks, I've been using ThrottleStop for years, and after following said guide every option was enabled, tweakable and working, including the possibility to undervolt the CPU which is unfortunately missing here in UXTU for some reason, even though I know the option actually exists for other CPUs.
I love the idea of having multiple custom presets, tweaking my dGPU directly from here, and even the possibility of enabling a universal upscaler in games... but I miss being able to undervolt! It is especially needed in summer due to the high temperatures, so I hope support for this and eventually other unsupported CPUs can be added.

![image](https://github.com/user-attachments/assets/96e9664d-ac23-413c-873f-addec299a61d)

**Comment by JamesCJ60** [comment]
Hi, I hope to add FIVR voltage control for supported Intel CPUs in the next release.

**Comment by ShyVortex** [comment]
Thank you so much!

**Comment by JamesCJ60** [comment]
This should now be working as of the latest build.
