### ISSUE TITLE
[BUG] A wrong command line within premade preset "Performance" 

### ISSUE THREAD

**Issue by mishuha** [JamesCJ60/Universal-x86-Tuning-Utility#225]
The program has 4 command lines for presets:

Eco: 
--tctl-temp=95 --ppt-limit=65000 --edc-limit=90000 --tdc-limit=90000 

Balanced: 
--tctl-temp=95 --ppt-limit=95000 --edc-limit=130000 --tdc-limit=130000 

Performance: 
--tctl-temp=95 --ppt-limit=125000 --edc-limit=142 --tdc-limit=142000 

Extreme: 
--tctl-temp=95 --ppt-limit=170000 --edc-limit=230000 --tdc-limit=230000 

And in Performance "--edc-limit=**142**" instead of "--edc-limit=**142000**" seems like as a typo that leads to actual performance loose after activation.
![изображение](https://github.com/user-attachments/assets/393202db-e37c-45b6-8de0-6cc231676d39)

CPU: Ryzen 9 5900X
![изображение](https://github.com/user-attachments/assets/78005369-17fd-480d-98cb-f36957eb1236)

Reproducible on program version 2.2.5.0
![изображение](https://github.com/user-attachments/assets/162974c1-fe80-442c-9796-9bddb89da581)

**Desktop:**
OS: Windows 10 Pro 22H2

**Comment by JamesCJ60** [comment]
Thank you for bringing this to my attention. I will get this fixed in the next release.

**Comment by JamesCJ60** [comment]
This should be fixed as of the latest build.

**Comment by mishuha** [comment]
Not fixed in V2.3.2 stable.
There are no presets at all.  UXTU line commands are empty for all presets.
![изображение](https://github.com/user-attachments/assets/f38dbaa8-08b1-44c8-9c44-5907c215d8c7)
