### ISSUE TITLE
[BUG] Partition table corruption after a few hours

### ISSUE THREAD

**Issue by bbanho** [JamesCJ60/Universal-x86-Tuning-Utility#236]
**Describe the bug**

Windows drive partition table corruption when running the software for about 6 hours. Happened a dozen times and I could not retrieve any dump or log file after crash so it had me imaging my whole filesystem until finding out it was caused by the utility. Many EFI and WinRE partition files remained broken after rewriting of the p table backup. Noticed abnormal instability at high ram usage. My SSD is a suspicious generic cheap drive, but the problem had been gone for a week now. I'll try replicate the crash anytime soon.

**To Reproduce**
Steps to reproduce the behaviour:

_**Expected behaviour**

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 11 22H2]_

**Additional context**

Don't hesitate asking me more info.

Computer:      LENOVO IdeaPad 3 15ALC6
CPU:           AMD Ryzen 5 5500U (Lucienne, LCN-A1)
               2100 MHz (21.00x100.0) @ 4042 MHz (40.50x99.8)
Motherboard:   LENOVO LNVNB161216
BIOS:          GLCN52WW, 12/09/2022
Chipset:       AMD Promontory/Bixby FCH
Memory:        8192 MBytes @ 1597 MHz, 22-22-22-52
               - 4096 MB PC25600 DDR4 SDRAM - Smart Modular SMS4WEC3C0K0446SCG
Graphics:      AMD Lucienne - Internal GPU [Lenovo]
               AMD Radeon Vega, 2048 MB DDR4 SDRAM
Drive:         WDC WD10SPZX-75Z10T1, 976.8 GB, Serial ATA 6Gb/s @ 6Gb/s
Drive:         Patriot M.2 P300 128GB, 125.0 GB, NVMe
Sound:         ATI/AMD Renoir/Cezanne - Display HD Audio Controller
Sound:         AMD Zen - Audio Processor - HD Audio Controller
Network:       RealTek Semiconductor RTL8822CE Wireless LAN 802.11ac PCI-E NIC
OS:            Microsoft Windows 11 Professional (x64) Build 22631.4112 (23H2)

**Comment by bbanho** [comment]
Hardware failure under sustained load, the utility was just boosting it into a quicker crash. I'm feeling into using it to underclock lol

appreciate the tool, pretty useful no matter watt xD

**Comment by shadowsofthesun** [comment]
This should be closed since the program is just exposing an underlying hardware failure?

**Comment by bbanho** [comment]
Made more tests and has to be.  Hardware issues. Thank you for attention.
