### ISSUE TITLE
Universal Tuning Utility is Blocking Nvidia from switching display mode (Optimus dedicated vs integrated)

### ISSUE THREAD

**Issue by papaytl185** [JamesCJ60/Universal-x86-Tuning-Utility#24]
Universal Tuning Utility is Blocking Nvidia from switching display mode (Optimus dedicated vs integrated) (pre release 9.2)

**Comment by fabiomfpinto** [comment]
I stated exactly the same issue even on version 1.0.0

**Comment by JamesCJ60** [comment]
Hi, go to this menu in Windows settings and force UXTU to use ur iGPU by default instead:
![image](https://user-images.githubusercontent.com/20888782/213931977-b6919b21-57b8-441a-a574-ab941857d582.png)
