### ISSUE TITLE
CPU curve optimizer no effect on R7 5800H[BUG]

### ISSUE THREAD

**Issue by EbicKachow** [JamesCJ60/Universal-x86-Tuning-Utility#26]
**Describe the bug**
CPU Curve Optimizer has no effect on MHz or Voltage, leaving no effect on performance or temperatures
**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 11 22H2]
Windows 10 21H2

**Additional context**
Using gaming laptop with Ryzen 7 5800H and 3070

**Comment by JamesCJ60** [comment]
Ryzen 7 5800H does not support Curve Optimiser
