### ISSUE TITLE
[BUG] MP1 AM5 mailbox doesn't seem to be working/present

### ISSUE THREAD

**Issue by irusanov** [JamesCJ60/Universal-x86-Tuning-Utility#269]
**Describe the bug**
The MP1 addresses for AM5 seem to be incorrect
https://github.com/JamesCJ60/Universal-x86-Tuning-Utility/blob/7c762bbfaf7f1ebcf07780a9668397ab847789f6/Universal%20x86%20Tuning%20Utility/Scripts/AMD%20Backend/RyzenSmu.cs#L315

Even the simple 0x1 command does not work and some of the other commands lock the smu and the system needs to be rebooted in order to get it operational again.

I still use the old MP1 addresses that seem to be working on Raphael and GraniteRidge.
```
Mp1Smu.SMU_ADDR_MSG = 0x3B10530;
Mp1Smu.SMU_ADDR_RSP = 0x3B1057C;
Mp1Smu.SMU_ADDR_ARG = 0x3B109C4;
```

**Comment by JamesCJ60** [comment]
Thank you for pointing this out, irusanov.
