### ISSUE TITLE
Undervolt feature no longer functioning on Ryzen 6900HS [BUG]

### ISSUE THREAD

**Issue by l0lGhostlxl** [JamesCJ60/Universal-x86-Tuning-Utility#29]
**Describe the bug**
The undervolt is not doing anything as setting the value to anything like -30 or even to -1000 does not cause it to immediately crash.

**To Reproduce**
Steps to reproduce the behaviour:
Set the undervolt to -30 or anything very low that should crash a laptop

**Expected behaviour**
The laptop should crash as the undervolt of -30 or -1000 should crash it as it would be unstable

**Desktop (please complete the following information):**
Windows 11 22H2

**Comment by JamesCJ60** [comment]
Hi, firmware (AGESA) for Ryzen laptops was updated with limits for curve optimiser that no longer allows anything lower than -30 to be set.
