### ISSUE TITLE
How to view if changed values are really applied?

### ISSUE THREAD

**Issue by rama982** [JamesCJ60/Universal-x86-Tuning-Utility#3]
There is no monitor for it like the ryzen controller.

**Comment by Wangyunche** [comment]
hwinfo64 may help

**Comment by JamesCJ60** [comment]
For supported APUs, the below menu is available to view all those details. Currently, supported APUs range from the 4000 series to 5000 series, using the newest PMTable for each generation.
 
![image](https://user-images.githubusercontent.com/20888782/183314606-4ec07db6-c63e-41c9-b5d7-66f997cbd8a0.png)

**Comment by rama982** [comment]
@JamesCJ60 no suppport for 3000 series?
