### ISSUE TITLE
[FEATURE REQUEST] Value monitoring.

### ISSUE THREAD

**Issue by cronyakatsuki** [JamesCJ60/Universal-x86-Tuning-Utility#31]
I would like for uxtu have an option to monitor one specific value for example `tctl-temp` and check it for example every 5 seconds, if it isn't the same then apply the profile again.

I have been very frustated with current reapply method since if for example settings get changed at the 10 seconds mark there are 50 seconds more to go and that can lead to either lower performance or to thermal trothling. To combat that I had it set to something like every 5 seconds, but that led to cpu spikes every 5 seconds and lag at that exact moment.

**Comment by JamesCJ60** [comment]
There is no easy way of handling this with the suggested method still leading to extra cpu cycles being used.
