### ISSUE TITLE
[BUG Sudden freezing on 6000 series APUs.

### ISSUE THREAD

**Issue by botigeri** [JamesCJ60/Universal-x86-Tuning-Utility#34]
My laptop - Lenovo Yoga 7 14ARB7 - is freezing randomly when using the software to modify the wattage.

The problem doesn't seem to be temperature related as it happens both when it's pulling 36 watts at 90 degrees and when it's pulling eg. 5 watts at 45 degrees.
It happens both with the presets and when setting the wattage manually.
Reportedly - discord - it happens on 6600U, 6800U and 6900HS laptops.

The only thing we have noticed is that AIDA64 and HWinfo cpu package wattage readings go to 0.0 and stop updating a few seconds before the freeze happens.

 - OS Version: Windows 11 22H2

**Comment by JamesCJ60** [comment]
Should be fixed as of the latest release.
