### ISSUE TITLE
[BUG] UTU crashes on wake

### ISSUE THREAD

**Issue by Interinactive** [JamesCJ60/Universal-x86-Tuning-Utility#35]
**Describe the bug**
Razer Blade 14

When putting the laptop to sleep with the app open, it crashes when the computer wakes later on.

**To Reproduce**
Steps to reproduce the behaviour:
1. Put laptop to sleep for a while
2. Come back, UTU quits immediately

**Expected behaviour**
The app to remain open. All I am using it for is setting a max temp of 80 degrees.

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: Windows 11, latest update. Everything else updated.

**Additional context**

**Comment by JamesCJ60** [comment]
Hi, this should no longer be an issue on newer builds.
