### ISSUE TITLE
Not Able to Reset to Default Settings in Ryzen 6800H[BUG]

### ISSUE THREAD

**Issue by sam20081990** [JamesCJ60/Universal-x86-Tuning-Utility#36]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Main Page'
2. Click on 'Performance'
3. Unable to Reset to Default Behavior

**Expected behaviour**
If I reset to default, the boost functionality should go back to normal. Instead the CPU is locked to VID 1.2V and max TDP of 30W instead of default 1.4V and max TDP of 45W.

When the windows is restarted the CPU goes back to default behaviour but as soon as a game is started it seems the boost and TDP gets locked even if the "Auto Reaplly", "Start on System Reboot" and "Apply OC Menu options on start" are not checked.

Performance of the CPU is reduced even though I have thermal headroom. Is there a way to restore the default CPU functionality for good till this issue can be fixed?

**Screenshots**
![boost stuck](https://user-images.githubusercontent.com/124224536/216217087-69f3feb6-8d71-4ab7-943c-fec4b0c4c9a0.jpg)

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 11 22H2]

**Additional context**

**Comment by JamesCJ60** [comment]
This is a system issue and not an issue that relates to UXTU, all changes made in UXTU get 100% reverted on system restart/reboot. Contact your OEM to notify them of the issue.
