### ISSUE TITLE
这个软件支持AMD R7 5800H处理器降压吗

### ISSUE THREAD

**Issue by zx2021** [JamesCJ60/Universal-x86-Tuning-Utility#4]
Does the software support the buck of AMD R7 5800h Processor?
这个软件支持AMD R7 5800H处理器降压吗

**Comment by JamesCJ60** [comment]
Yes, UXTU supports the following:

- Ryzen APUs: 2000 series and newer.

- Ryzen CPUs: 3000 series and newer.

- Intel CPUs: 4th gen and newer.
