### ISSUE TITLE
App closing on battery power

### ISSUE THREAD

**Issue by MrHumanRebel** [JamesCJ60/Universal-x86-Tuning-Utility#40]
Hi!

While my G14 2021 laptop is plugged in the app is working flawlessly.
As soon as I unplug it or start the computer on battery, the app instantly crashes or not starting at all.
If I restart it manually, it is working fine again.
I don't have any conflicting apps installed.

App version number: V1.0.3 stable
OS: Windows 11 latest version stable 2023-02-09

Settings:
<img width="500" alt="image" src="https://user-images.githubusercontent.com/80947401/217836028-31d12436-7160-418c-bb67-fd0c711b511b.png">

Thanks in advance!

**Comment by JamesCJ60** [comment]
Hi, this issue should be fixed as of the latest beta build.
