### ISSUE TITLE
[BUG] resolution is incorrect on IdeaPad Slim 5

### ISSUE THREAD

**Issue by Mattwmaster58** [JamesCJ60/Universal-x86-Tuning-Utility#41]
**Describe the bug**
![image](https://user-images.githubusercontent.com/26337069/217921929-81c3e815-64a1-4bd5-8403-64f0a09157e7.png)

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to project snowdrop

**Expected behaviour**
Correct display resolution

**Desktop (please complete the following information):**
 - OS Version: Windows 10 21H2

**Comment by l0lGhostlxl** [comment]
I also do not get the correct resolution in the application as well 
<img width="802" alt="image" src="https://user-images.githubusercontent.com/89779681/217951172-a710bd20-c7b2-4e40-a493-5fa535c156a8.png">

**Comment by JamesCJ60** [comment]
I’m currently clearing all UXTU V1.0.0 issues now that UXTU V2.0.0 is in beta testing. If the issue still persists in UXTU V2.0.0 feel free to reopen the issue.
