### ISSUE TITLE
[BUG]Malware Detection from Malwarebytes

### ISSUE THREAD

**Issue by Arkthurs** [JamesCJ60/Universal-x86-Tuning-Utility#43]
After clicking to run Universal x86 Tuning Utility.exe Malwarebytes quarantined it under: Malware.AI.4003546723.

**Comment by JamesCJ60** [comment]
Hi, due to using dlls such as WinRing0x64.dll to gain proper access to your device's hardware UXTU gets falsely flagged as a virus.
