### ISSUE TITLE
[BUG]When trying to Universal x86 Tuning Utility it tells me i have to install something from microsoft store, but it gets me to a nonexistant page

### ISSUE THREAD

**Issue by danielpuchej** [JamesCJ60/Universal-x86-Tuning-Utility#44]
![image](https://user-images.githubusercontent.com/124250080/219898741-27ec2f80-42ff-48af-b16c-c539d85d06ed.png)

**Comment by JamesCJ60** [comment]
Hi, ensure you are trying to open Universal x86 Tuning Utility.exe and have the required .NET/.NET framework versions installed.
