### ISSUE TITLE
[BUG] Sensors stopped working

### ISSUE THREAD

**Issue by killerart** [JamesCJ60/Universal-x86-Tuning-Utility#49]
The info tab stopped showing any info. All the sensors values are 0.

It worked before, but one day it stopped working. Didn't really change anything about my system.

**Screenshots**
![image](https://user-images.githubusercontent.com/48909985/227059025-142cb3f6-dbe9-428d-a3d1-ae52567b5ee2.png)

**Desktop (please complete the following information):**
 - OS Version: Windows 10 22H2 build 19045.2728
 - CPU: AMD Ryzen 5 5900HX

**Comment by marwan4mr** [comment]
i have  the same issue with 5800h lenovo legion

**Comment by stujii** [comment]
+1 (lenovo legion 5800h)

**Comment by JamesCJ60** [comment]
I’m currently clearing all UXTU V1.0.0 issues now that UXTU V2.0.0 is in beta testing. If the issue still persists in UXTU V2.0.0 feel free to reopen the issue.

**Comment by killerart** [comment]
@JamesCJ60 well, the issue fixed itself without me doing anything. I didn’t update windows, bios or the app. Started the laptop one day and it worked.
