### ISSUE TITLE
Processor power consumption is limited to 54 watts after undervoltage using this software

### ISSUE THREAD

**Issue by ll-yy-pp** [JamesCJ60/Universal-x86-Tuning-Utility#5]
My processor is R5 4600H After I used the Universal x86 Tuning Utility to undervoltage and unlock current limit , the processor power consumption was limited to 54 watts and I couldn't restore it. I tried restarting my computer and updating the BIOS but couldn't change it.

**Comment by JamesCJ60** [comment]
Hi, it is impossible for any changes made with this software to remain after a reboot as the APU’s SMU is reverted back to stock after a system shutdown.
