### ISSUE TITLE
Doesn't work on ONEXPLAYER 2 (6800U).]

### ISSUE THREAD

**Issue by mineblack77** [JamesCJ60/Universal-x86-Tuning-Utility#51]
I used it on my ONEXPLAYER 2, but with the officially supported power controller, I was able to set the CPU TDP in the range of 4-28W, but with this software, it never exceeded the maximum of 28W, didn't work.
I don't know why, but only lowering the frequency of the integrated graphics (Radeon) worked.
Could you make it possible to control the TDP?
Thank you for your support.

This text has been translated from Japanese to English by Google Translate, so please understand that there may be unnatural translations.

**Comment by JamesCJ60** [comment]
I’m currently clearing all UXTU V1.0.0 issues now that UXTU V2.0.0 is in beta testing. If the issue still persists in UXTU V2.0.0 feel free to reopen the issue.
