### ISSUE TITLE
[BUG] APU Spesific Presets are stopping working while gaming

### ISSUE THREAD

**Issue by LatifSC** [JamesCJ60/Universal-x86-Tuning-Utility#52]
**Describe the bug**
APU Spesific presets are only working on desktop. While gaming it goes back to default TDP in 1-2 minutes.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Project Snowdrop'
2. Click on 'APU Spesific Presets'
3. Preset applies
4. Open up / switch to a game

**Expected behaviour**
Stay at the selected settings

**Screenshots**
![image](https://user-images.githubusercontent.com/68355853/232259085-b8523e5e-7740-42ef-befb-e700d57a9ed5.png)

![image](https://user-images.githubusercontent.com/68355853/232259198-e50f7edc-fe76-4529-ba81-b4d37ab1d084.png)

Laptop: ASUS TUF Gaming FX505DU
 - OS Version: Windows 11 22H2 - 22621.1413
 - Ryzen 7 3750H
 - GTX1660Ti Mobile 6GB
 - 8X2 2400Mhz RAM

**Comment by JamesCJ60** [comment]
I’m currently clearing all UXTU V1.0.0 issues now that UXTU V2.0.0 is in beta testing. If the issue still persists in UXTU V2.0.0 feel free to reopen the issue.
