### ISSUE TITLE
[BUG] Process gets killed after a while in windows 10 x64

### ISSUE THREAD

**Issue by mrtaichi** [JamesCJ60/Universal-x86-Tuning-Utility#53]
Process gets automatically killed after a while in windows 10 x64. The time is not specific. It could be 5, 10 or 20 hours or more.
I am using 4800H cpu in a Lenovo Legion 5 laptop.

**Comment by JamesCJ60** [comment]
I’m currently clearing all UXTU V1.0.0 issues now that UXTU V2.0.0 is in beta testing. If the issue still persists in UXTU V2.0.0 feel free to reopen the issue.
