### ISSUE TITLE
[BUG]curve optimiser settings not support 7735h

### ISSUE THREAD

**Issue by philipzha** [JamesCJ60/Universal-x86-Tuning-Utility#55]
**Describe the bug**
A clear and concise description of what the bug is that i change curve optimiser settings -all core to -30 even to -99,but it doesn't work.

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 11 22H2]

**Additional context**

**Comment by JamesCJ60** [comment]
Hi, this option only works on Ryzen 9’s are the 4000 series.

**Comment by philipzha** [comment]
thanks,that' a sad story
