### ISSUE TITLE
[BUG] Curve Optimizer Missing on the new version 2.0

### ISSUE THREAD

**Issue by kalimaenergy** [JamesCJ60/Universal-x86-Tuning-Utility#57]
Hello,

Thank for your amazing software , I use it everyday , very powerfull.
Little issue with the new version , probably normal with current move to new design.

**Describe the bug**
Tab for make Curve optimizer setting missing on New Version 2.0 VS V1.1.0 Beta 5

**To Reproduce**
Steps to reproduce the behaviour:
Install and open new version 2.0 Beta 0 to a Laptop with 5900HX

**Comment by mlubert** [comment]
Hey how was this fixed.
