### ISSUE TITLE
[FEATURE REQUEST] more features that ryzen controller already has that i and maybe everyone will need it related to vram vs igpu vs cpu

### ISSUE THREAD

**Issue by dotienanhvietnam** [JamesCJ60/Universal-x86-Tuning-Utility#63]
i want to add cpu and igpu fixed clock speed eg cpu will fix clock speed at 2100GHz and igpu clock speed at 1600mhz if possible you can also add speed lock feature of vram ( MSI afterburner shows as MEM by default ) those are the features I wanted to add because I just switched from ryzen controller to Universal x86 Tuning Utility
![blob](https://user-images.githubusercontent.com/132206353/235612385-f2fe61b9-0f77-46f5-9f13-2387e98d1a55.jpg)

**Comment by JamesCJ60** [comment]
This has been address as of the latest release.
