### ISSUE TITLE
Main window appears on Alt-tab menu

### ISSUE THREAD

**Issue by VinhCastle** [JamesCJ60/Universal-x86-Tuning-Utility#64]
When I minimize the main window to tray, it is minimized to tray but it is still there on the Alt-tab menu.

**Comment by l0lGhostlxl** [comment]
That's probably an intended feature since it's also in Armoury Control as well. It's pretty useful to be honest.

**Comment by JamesCJ60** [comment]
Hi, this is not an issue and is as intended.
