### ISSUE TITLE
Closes after opening the premade section [BUG]

### ISSUE THREAD

**Issue by rugo-cafe** [JamesCJ60/Universal-x86-Tuning-Utility#67]
If i click in the premade presets section either by the sidebar icon, or the button below the welcome message, it closes itself instantly.

V2.0.0 Beta Build 3 
OS Version: Win 11 22H2
CPU: Ryzen 5 3500U

**Comment by JosivaldoLira123** [comment]
I was using Win 11 22H1 and there was no problem with the app. Yesterday I formatted my PC and installed Win 11 22H2, now I have the same problem as you. Seems to be a bug with this version of Windows.

**Comment by JosivaldoLira123** [comment]
If you already used the app in this version before, it could be a bug with the processor or even the driver, my processor is the R5 5500u and the driver version is 23.4.3. I hope the developer fixes this problem soon.

**Comment by JamesCJ60** [comment]
Hi, this should be fixed as of the latest build.

**Comment by MentolosNokedli** [comment]
Hi, on my Lenovo 82jy Legion 5 17ach6h (CPU 5800H) whit Win 11 full updated only the  V1.0.3 Stable version is working.
All other version crashes @ Premade and  in Custome iff i press the Apply current settings or Save Buttion. Sorry for bad English

**Comment by MortiMaus** [comment]
Hi, have the same issue with closing the application after clicking the premade button. 
Im on an Asus TUF A17 with 6800h. 
Im on 2.0.0.8 my os is Win11pro 22H2
Any help is welcome. :-)

**Comment by jwagra** [comment]
Hi, i have the same issue on [V2.0.0 - Beta 6.1] on my Acer Nitro 5 - Ryzen 6600H with latest win11pro

**Comment by JamesCJ60** [comment]
Hi, this issue should now be fixed for everyone as of the latest beta.

**Comment by YegorStepanov** [comment]
beta7 is still crashing
