### ISSUE TITLE
Adaptive performance when toggled on shows a dll error[BUG]

### ISSUE THREAD

**Issue by l0lGhostlxl** [JamesCJ60/Universal-x86-Tuning-Utility#69]
**Describe the bug**
When I toggle it on it shows a dll error
**To Reproduce**
Steps to reproduce the behaviour:
1. Toggle it on

**Expected behaviour**
No errors

**Screenshots**
<img width="310" alt="image" src="https://github.com/JamesCJ60/Universal-x86-Tuning-Utility/assets/89779681/88f85478-aed7-448f-af8d-5fb0ea51361d">

**Desktop (please complete the following information):**
Edition	Windows 11 Home
Version	22H2
Installed on	‎20/‎03/‎2023
OS build	22621.1702
Experience	Windows Feature Experience Pack 1000.22641.1000.0

**Comment by l0lGhostlxl** [comment]
It also causes my laptop to crash after a bit as well. The laptop is a flow x16 with a Ryzen 9 6900HS 2022 edition

**Comment by siloli** [comment]
Hi,
Same error here with the flow x13 Ryzen 9 5900HS.
Windows 11 Pro Build 22621

**Comment by JamesCJ60** [comment]
Hi, this should be fixed as of the latest build.

**Comment by l0lGhostlxl** [comment]
The new build just seems to crash immediately after launching.

**Comment by l0lGhostlxl** [comment]
Never mind a quick restart has fixed it, and the app and feature is working now. Thank you for your help.
