### ISSUE TITLE
Frame Interpolation

### ISSUE THREAD

**Issue by marcos32123** [JamesCJ60/Universal-x86-Tuning-Utility#70]
I wanted to know if there is a possibility to create a frame generator for this application?
type frame generator of dlss3.0 or fsr 3.0
[https://www.youtube.com/watch?v=oSYyVtjPjwA](url)

**Comment by JamesCJ60** [comment]
Hi, adding any kind of frame generation would have high hardware costs and could drastically increase latency making it untenable.
