### ISSUE TITLE
[BUG] Ryzen 7 4750U - ThinkPad L15 Gen 1 AMD - causes malfunction

### ISSUE THREAD

**Issue by gokcekurtarioso** [JamesCJ60/Universal-x86-Tuning-Utility#74]
This is for Version 2.00 Beta 6, with Desktop Runtime 7.0.5 installed. (Windows 10 22H1), Ryzen 7 4750U Renoir APU. 

When I attempt to launch UXTU, the window doesn't show up and operating system starts malfunctioning. Start menu and popup menus from taskbar become unresponsive. Cannot start the Task Manager and needed to shut the computer down using power button. 

When I reopen the computer, it is recurring.  Everytime I try to use, i need to uninstall and reinstall UXTU from msi file.

**Comment by JamesCJ60** [comment]
Hi, this should no longer be an issue as of the latest betas.
