### ISSUE TITLE
App allows multiple instances

### ISSUE THREAD

**Issue by Aashishkebab** [JamesCJ60/Universal-x86-Tuning-Utility#76]
**Describe the bug**
Allows more than one instance, which can cause issues.

**To Reproduce**
Simply launch the application multiple times from Start.

**Expected behaviour**
A second instance should detect the first and cancel opening.

**Screenshots**
![image](https://github.com/JamesCJ60/Universal-x86-Tuning-Utility/assets/25588487/c46d2096-ab29-4b17-ada3-82d2ff95fb6b)

**Desktop (please complete the following information):**
Windows 11 latest version

**Comment by JamesCJ60** [comment]
Hi, this is no longer an issue as of the latest beta.
