### ISSUE TITLE
Poor documentation

### ISSUE THREAD

**Issue by Aashishkebab** [JamesCJ60/Universal-x86-Tuning-Utility#77]
**Describe the bug**
Also, there isn't good documentation as to what each feature is. For example, there is no good explanation for what Adaptive Mode is and I don't understand it or any of the items in the dropdown. I also don't understand what "Auto Reapply (s)" is. Also "Reapply on start" isn't intuitive when you set the app to start on boot and have automation set up.

The fan control page is completely confusing and I have no idea how to use it by looking at it.

There should exist some user documentation on all the features and how to use them.

**Comment by realNZZN** [comment]
Still have no idea what adaptive mode does, as its description is very vague. From what I can tell it's either a per-application profile switcher, or something trying to lower CPU clock to prioritise GPU clock in APUs?
