### ISSUE TITLE
Discharge automation keeps clearing upon app restart

### ISSUE THREAD

**Issue by Aashishkebab** [JamesCJ60/Universal-x86-Tuning-Utility#78]
**Describe the bug**
When the app restarts, whatever value was in the Discharge option is cleared.

**Expected behaviour**
Values to be remembered.

**Screenshots**
![image](https://github.com/JamesCJ60/Universal-x86-Tuning-Utility/assets/25588487/1ba08ec8-4cf1-4714-bd3a-c0787c9fd05f)

**Desktop (please complete the following information):**
 - OS Version: Windows 11

**Comment by JamesCJ60** [comment]
Hi, this issue should now be fixed as of the latest beta.
