### ISSUE TITLE
Re-applying settings on boot doesn't use the right profile

### ISSUE THREAD

**Issue by Aashishkebab** [JamesCJ60/Universal-x86-Tuning-Utility#79]
**Describe the bug**
When re-applying settings on boot, it should look at the automation and apply the profile based on the power supply state. Instead, it literally applies what was last used, so if I shut down the computer while plugged in but boot while unplugged, the power profile for plugged in will be used, wasting battery. And vice versa.

**Expected behaviour**
The app should solely change power profile based on the charge/discharge state if those profiles are set, rather than waiting for that even to trigger (unplug/plug in).

**Desktop (please complete the following information):**
 - OS Version: Windows 11

**Additional context**
I apologize for the sheer number of bugs I've reported, but there are a lot of bugs.

**Comment by JamesCJ60** [comment]
Hi, this is no longer an issue as of the latest beta.
