### ISSUE TITLE
Auto-reapply allows unallowed values

### ISSUE THREAD

**Issue by Aashishkebab** [JamesCJ60/Universal-x86-Tuning-Utility#80]
**Describe the bug**
The auto-reapply (s) allows entries of values above 99, but 99 appears to be the maximum value. Anything above that will result in the last digit being truncated upon app re-launch.

**To Reproduce**
Steps to reproduce the behaviour:
1. Type a value above 99 into the field.
2. Close app.
3. Re-open app and check value.

**Expected behaviour**
A limit on the field values

**Desktop (please complete the following information):**
 - OS Version: Windows 11

**Comment by JamesCJ60** [comment]
Hi, this is no longer an issue as of the latest beta.
