### ISSUE TITLE
[BUG] On AMD Ryzen 7 5800H the temp not lock

### ISSUE THREAD

**Issue by vincenzogovernali** [JamesCJ60/Universal-x86-Tuning-Utility#81]
Hi all, I have an AMD Ryzen 7 5800H with a radeon video card.
I am coming from the old Ryzen Controller software which always worked for me on this machine and never gave me any problems.
Today I wanted to try your software but I could not with any section to lock the temperature of my APU.
I tried custom and adaptive and the software can't lock the temperature at 85°. 
I ran the tests on CS GO and Call of Duty Warzone 2 which never exceeded 85° on Ryzen Controller

**Comment by JamesCJ60** [comment]
Hi, this issue should now be fixed as of the latest beta. Although, the option is only a soft throttle limit so the APU will go over if adequate cooling is not provided.
