### ISSUE TITLE
[BUG] Installer refuses to install anywhere than on my Z: drive.

### ISSUE THREAD

**Issue by acolwill** [JamesCJ60/Universal-x86-Tuning-Utility#88]
**Describe the bug**
Installer refuses to install anywhere than on my Z: drive.

**To Reproduce**
Install application, any options.
Application simply installs into the root of the drive with the last drive letter (z)

**Expected behaviour**
Application should install where I ask it to install.

**Screenshots**
![image](https://github.com/JamesCJ60/Universal-x86-Tuning-Utility/assets/42255153/cc1da1f5-b888-4c0a-acd6-cd7875bc6643)
![image](https://github.com/JamesCJ60/Universal-x86-Tuning-Utility/assets/42255153/0edb7dc2-3b88-4c6d-b668-781cdbf80e45)
![image](https://github.com/JamesCJ60/Universal-x86-Tuning-Utility/assets/42255153/0c22a707-4d1c-417e-9f1f-1e038b78f4ad)
![image](https://github.com/JamesCJ60/Universal-x86-Tuning-Utility/assets/42255153/f36b3210-62d7-47bb-a178-03adce55d64d)
![image](https://github.com/JamesCJ60/Universal-x86-Tuning-Utility/assets/42255153/ddddc05a-5763-4f4b-a94f-235e7475ad6b)

**Desktop (please complete the following information):**
 Windows 10 22H2 Build 19045.3155

**Comment by JamesCJ60** [comment]
Hi, this is a Microsoft issue not a UXTU issue.

**Comment by acolwill** [comment]
Hi, how is this a Microsoft issue?
Having dealt with MS systems for 30+ years, this is the first time I've seen an installer routine ignore user options.

**Comment by JamesCJ60** [comment]
The installer used is from the Visual Studio installer package, which is both created and maintained by Microsoft.
https://marketplace.visualstudio.com/items?itemName=VisualStudioClient.MicrosoftVisualStudio2022InstallerProjects

**Comment by acolwill** [comment]
When I remove the drive letter mapping for Z:, the installer routine now installs to the root of D: and not within the directory structure specified.
Do you have a list of available command line switches, or a ZIP/7z download?

**Comment by acolwill** [comment]
This feels like an issue with the MSI

Installer log for UXTU
[uxtu.log](https://github.com/JamesCJ60/Universal-x86-Tuning-Utility/files/11927693/uxtu.log)

Installer log for QuickSFV (which also uses VS Installer Projects)
[quicksfv.log](https://github.com/JamesCJ60/Universal-x86-Tuning-Utility/files/11927698/quicksfv.log)
