### ISSUE TITLE
InstallDriver.exe ?

### ISSUE THREAD

**Issue by NostromoUS** [JamesCJ60/Universal-x86-Tuning-Utility#9]
Hi! First of all, great work on this and thank you!

I'd just like to ask what exactly does "InstallDriver" installs as it runs when you open the utility for the first time. Does it permanently alter anything? Can it be uninstalled?

Thanks!

**Comment by JamesCJ60** [comment]
Hi, it just makes sure that drivers that should be part of a normal Windows install are actually installed.

**Comment by eneskuluk** [comment]
I clicked to no once I saw the driver installation, Is there any downsides not allowing it to execute?
