### ISSUE TITLE
[BUG] HP 5825u

### ISSUE THREAD

**Issue by cvc2023** [JamesCJ60/Universal-x86-Tuning-Utility#91]
HP 445 g9 5825u not working
Tried downgrading the bios to 1.05 dated 01.22, same
Stock stapm is 30w
All I can get using the app is 15W stapm
Other params seem to remain stock

[table1.txt](https://github.com/JamesCJ60/Universal-x86-Tuning-Utility/files/11954831/table1.txt)

**Comment by eziaw** [comment]
did you resolve this bug somehow?

**Comment by JamesCJ60** [comment]
OEMs such as HP set strict hard limits that cannot be exceeded.
