### ISSUE TITLE
[FEATURE REQUEST] I want to add the ability to apply overclocking parameters right from the moment I open the PC or laptop

### ISSUE THREAD

**Issue by dotienanhvietnam** [JamesCJ60/Universal-x86-Tuning-Utility#99]
I have customized all the parameters, but every time I restart the laptop or open the laptop, those options have not been applied and only apply the parameters available in the software, so I want an option in the auto section. On the fan section, there is an option to apply overclocking parameters right from the start. Thank you for reading and creating this application thank you❤

![image](https://github.com/JamesCJ60/Universal-x86-Tuning-Utility/assets/132206353/a0a76e95-8621-4410-a400-73e2f3f8cc52)

**Comment by JamesCJ60** [comment]
Hi, such option already exists and is located within the settings menu.

**Comment by dotienanhvietnam** [comment]
I left my default GPU frequency at 800MHz but every time I turn off my
laptop and turn it back on, I use MSI Afterburner to check that the GPU
frequency is still working by default and I have to go into the app
settings and apply the saved settings again for my GPU frequency to work at
the level I leave


Vào Th 2, 24 thg 7, 2023 vào lúc 07:44 James Craddock-Jones <
***@***.***> đã viết:
